### ISSUE TITLE
Generated enum types can fail if comments with commas in them

### ISSUE THREAD

**Issue by stevecasl** [SunsetQuest/CppHeaderToCSharpConverter#1]
Running on a source file with the following text:

`
typedef enum
{
	MI_INVALID_0 = 0, 	// do not modify
	MI_OOB,				// do not modify
	MI_ErrorMessage,	// do not modify
	MI_MessageCode,		// do not modify

	// NOTE: try to put messages that are likely to be used by *any* system in the first group, this may be fixed for these, sometime
	MI_REG_START, // used for looping
	MI_Fans = MI_REG_START, // fan data
	MI_Currents, // current data from water probe etc.
	MI_State1, // a regular dump of all data 1 (includes event data, allows synchronisation without restart)
	MI_State2, // a regular dump of all data 2 (ditto)
	MI_State3,
	MI_REG_END = MI_State3, // used for looping

	MI_INVALID_MAX = 0xFF // do not modify
} MsgIds_t;
`

And receive the following output
`
    [Flags]
    public enum MsgIds_t
    {
        MI_INVALID_0 = 0,
        MI_OOB,
        MI_ErrorMessage,
        MI_MessageCode,
        group,
        these,
        MI_REG_START,
        MI_Fans = MI_REG_START,
        MI_Currents,
        MI_State1,
        data,
        MI_State2,
        MI_State3,
        MI_REG_END = MI_State3,
        MI_INVALID_MAX = 0xFF // do not modify,
    };
`

I applied a minor patch to strip any comments out from the rows, diff below.
I'm using your tool in a multi-header use though, so I may send a few more fixes through, at the moment I have 20 files all with a constant class :). Apart from that, I'm hoping this will save me a bit of effort on keeping a embedded projects header files in step with the C# backend that is receiving messages from it.
Thanks for the work!

` 
cppHeaderParse/Program.cs | 1 +
 1 file changed, 1 insertion(+)

diff --git a/cppHeaderParse/Program.cs b/cppHeaderParse/Program.cs
index abccfff..bed3d4c 100644
--- a/cppHeaderParse/Program.cs
+++ b/cppHeaderParse/Program.cs
@@ -290,6 +290,7 @@ namespace cppHeaderParse
                         string rows = match.Groups["enum_rows"].ToString() + ",";
                         sb.AppendLine("    public enum " + name);
                         sb.AppendLine("    {");
+                        rows = Regex.Replace(rows, @"//.*", string.Empty);
                         MatchCollection items = Regex.Matches(rows,
                             @"\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*(?:\s*=\s*([^\,(?:\r?\n)\{\}\;]*?))?\s*,");
                         foreach (Match r in items)
`

**Comment by SunsetQuest** [comment]
That is wonderful. Thanks for catching that and fixing it.  I am glad to see you found it useful. 
Feel free to do a pull request or let me know if I should post the fix.

**Comment by SunsetQuest** [comment]
Hi Stevecasl, I did some updating to the enum code so your example should work now..

**Comment by stevecasl** [comment]
Tested out on Friday and works nicely, it even keeps the comments around, which is much better than my quick hack.

I did have another failure, this time as a crash. It looks like the classic:
`#ifdef DEBUG

#define SOMEFUNC() dostuff();

#else

#define SOMEFUNC()

#endif`

Causes an issue with the MatchCollection, as SOMEFUNC is already present. The issue is only on one file in my project, so I added another processor instruction, C2CS_FILE_SKIP to have it actually not process the file (I have a script converting all the headers in the embedded side).
When I find time I'll raise another issue and provide some sample data.
